version: "3.7"

services:
  web:
    build:
      context: .
    volumes:
    - ./backend:/app
    env_file:
      - .env
      - .env.db
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
     /wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
  db:
    image: mysql:8.0
    ports:
    - "3308:3306"
    env_file:
      - .env.db
    restart: on-failure
    volumes:
    - ./mysql:/var/lib/mysql